name: Build Project

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout lively.next
        uses: actions/checkout@v3
        with:
          repository: LivelyKernel/lively.next
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '18.12.1'
      - name: Install lively.next
        run: |
          chmod a+x ./install.sh
          ./install.sh
      - name: Checkout Project Repository
        uses: actions/checkout@v3
        with:
          path: local_projects/engageLively--galyleo-dashboard
      - name: Build Dashboard
        run: npm run build --prefix local_projects/engageLively--galyleo-dashboard
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: local_projects/engageLively--galyleo-dashboard/bin
            